# Generated by Django 3.0.5 on 2021-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filetype', models.CharField(max_length=50)),
                ('pic', models.ImageField(blank=True, upload_to='picture')),
            ],
        ),
    ]
